name: Docker Build & Push
on: push

jobs:
  deploy:
    name: Deploy
  
    runs-on: ubuntu-latest  
    
    steps:  
        - name: Checkout
          uses: actions/checkout@v2 

          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1


        - name: Login to Amazon ECR
          id: login-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
          

        - name: Build and push the tagged docker image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ secrets.REGISTRY }}  # 546752724724.dkr.ecr.us-east-1.amazonaws.com/ecr-aws-repo
            ECR_REPOSITORY: ${{ secrets.REPO_NAME }} # ecr-aws-repo
            IMAGE_TAG: Sample-app
          run: |
            docker build -t $ECR_REGISTRY.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

        
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: kdua1/berto-image
           
        - name: Build and push Docker image
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
           
       
  