name: Docker Build & Push
on: push

jobs:
  deploy:
    name: Deploy
  
    runs-on: ubuntu-latest  
    
    steps:  
        - name: Checkout
          uses: actions/checkout@v2 
         
        - name: listing directory
          run: ls .

          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1


        - name: Login to Amazon ECR
          id: login-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
          

        - name: Build and push the tagged docker image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ secrets.REGISTRY }}  # 546752724724.dkr.ecr.us-east-1.amazonaws.com/ecr-aws-repo
            ECR_REPOSITORY: ${{ secrets.REPO_NAME }} # ecr-aws-repo
            IMAGE_TAG: Sample-app
          run: |
            docker build -t $ECR_REGISTRY.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       
  
       
  